#!/bin/bash

script=$1
if [ "$script" = "" ]; then
    echo "Usage: $0 shader.frag"
    exit 1
fi

ip=192.168.1.127
echo "Assuming IP address $ip"

./GO $1
scp out.o root@$ip:alice5/gpu/drive
echo "Run \"./drive out.o\" on the ARM, then press Enter here."
read
scp root@$ip:alice5/gpu/drive/fpga.ppm .
imgcat fpga.ppm

