// Automatically generated by generate_ops.py. DO NOT EDIT.

InsnFunctionParameter,
InsnFunctionCall,
InsnLoad,
InsnStore,
InsnAccessChain,
InsnCompositeConstruct,
InsnCompositeExtract,
InsnConvertSToF,
InsnFAdd,
InsnFSub,
InsnFMul,
InsnFDiv,
InsnVectorTimesScalar,
InsnFOrdLessThan,
InsnReturn