#ifndef OPCODE_STRUCT_DECL_H
#define OPCODE_STRUCT_DECL_H

// Automatically generated by generate_ops.py. DO NOT EDIT.

struct InsnFunctionParameter;
struct InsnFunctionCall;
struct InsnLoad;
struct InsnStore;
struct InsnAccessChain;
struct InsnVectorShuffle;
struct InsnCompositeConstruct;
struct InsnCompositeExtract;
struct InsnConvertFToS;
struct InsnConvertSToF;
struct InsnFNegate;
struct InsnIAdd;
struct InsnFAdd;
struct InsnFSub;
struct InsnFMul;
struct InsnFDiv;
struct InsnFMod;
struct InsnVectorTimesScalar;
struct InsnDot;
struct InsnLogicalNot;
struct InsnSelect;
struct InsnIEqual;
struct InsnSLessThan;
struct InsnFOrdEqual;
struct InsnFOrdLessThan;
struct InsnFOrdGreaterThan;
struct InsnFOrdLessThanEqual;
struct InsnFOrdGreaterThanEqual;
struct InsnPhi;
struct InsnBranch;
struct InsnBranchConditional;
struct InsnReturn;
struct InsnReturnValue;
struct InsnGLSLstd450FAbs;
struct InsnGLSLstd450Floor;
struct InsnGLSLstd450Sin;
struct InsnGLSLstd450Cos;
struct InsnGLSLstd450Atan;
struct InsnGLSLstd450Atan2;
struct InsnGLSLstd450Pow;
struct InsnGLSLstd450FMin;
struct InsnGLSLstd450FMax;
struct InsnGLSLstd450Length;
struct InsnGLSLstd450Distance;
struct InsnGLSLstd450Cross;
struct InsnGLSLstd450Normalize;

#endif // OPCODE_STRUCT_DECL_H
