#!/usr/bin/env bash

interpret=true
compile=false
simulate=false

if [ "$1" == "--compile" ]; then
    compile=true
    interpret=false
    shift
elif [ "$1" == "--sim" ]; then
    compile=false
    interpret=false
    simulate=true
    shift
elif [ "$1" == "--all" ]; then
    compile=true
    simulate=true
    shift
fi

if [ "$1" == "" ]
then
    shaders="red_green func_test creation define wavy dans_drews_poster lk wetrock flirt"
else
    shaders="$*"
fi

echo 
for shader in $shaders
do
    echo "============================================== $shader"
    if [ "$interpret" = true ]; then
        ./shade --term -f 90 90 shaders/$shader.frag
        mv image0090.ppm $shader-interpret.ppm
    fi
    if [ "$compile" = true -o "$simulate" = true ]; then
        rm x.o
        ./shade -c -O -o x.s shaders/$shader.frag > /dev/null && \
        ./as -v x.s > x.lst
    fi
    if [ "$compile" = true -a -e x.o ]; then
        ./emu --subst -f 90 --term x.o && \
        mv emulated.ppm $shader-compile.ppm
    fi
    if [ "$simulate" = true -a -e x.o ]; then
        ./gpu/sim/obj_dir/VMain -j 1 -f 90 --term x.o && \
        mv emulated.ppm $shader-simulate.ppm
    fi
done

