#!/usr/bin/env bash

if [ "$1" == "--compile" ]
then
    compile=true
    shift
else
    compile=false
fi

if [ "$1" == "" ]
then
    shaders="func_test creation define lk wavy wetrock flirt"
else
    shaders="$*"
fi

echo 
for i in $shaders
do
    echo "============================================== $i"
    if [ $compile = true ]; then
        ./shade -c -s -O -o x.s shaders/$i.frag && \
            ./as x.s && \
            ./gpuemu -f 90 --term x.o && \
            mv emulated.ppm $i.ppm
    else
        ./shade --term -f 90 90 shaders/$i.frag
        mv image0090.ppm $i.ppm
    fi
done

